### ISSUE TITLE
Move Independent Repos as Submodules

### ISSUE THREAD

**Issue by malife** [Sharonrab/SLUGS2-plus#1]
Currently _MAVLink_ and _clib_ are located inside the repo in the branch AUAV3_AND_SLUGS_SENSOR. It is strongly recommended that these are moved to git submodules as then you can have independent repositories and reuse these for the GS as you will need the SLUGS dialect for the GS.

**Comment by Sharonrab** [comment]
Yes you are right I'll fix it when we combine the work with Marchelo 

SR iPhone

**Comment by manora** [comment]
Would we like to move to the current simulink file format?

**Comment by Sharonrab** [comment]
Yes I'd like that, although I'm still working locally on 2011b. 
I can switch right a way. 

SR iPhone
